### ISSUE TITLE
Numerical issues in ERA5 data

### ISSUE THREAD

**Issue by timtroendle** [FRESNA/atlite#17]
I am using ERA5 runoff data to determine inflow time series for hydro power stations. The time series contain large negative values (-1e5) which look odd as they physically don't make sense.

I tried to trace them back to their origin. I am not exactly sure where and why this happens, but I am pretty sure it happens within `cutout.prepare()`: I ran [a comparison](https://gist.github.com/timtroendle/832ea97fc3f594560ce7dcaf95af4fe5) of data downloaded with `atlite` and data downloaded directly from `CDS` and found that those values deviate slightly and that runoff data is always >= 0 for raw CDS data, but can be <0 for atlite data.

The differences are tiny and very likely based on numerics. I am still reporting this here for three reasons: First, they may be tiny after download, but blow up to -1e5 in my case for inflow data. Second, because the data is not processed and because it should always be stored as float32, I don't exactly understand why the data changes. Third, this report may be of help for others running into the same issue.

Atlite version: [62897](https://github.com/FRESNA/atlite/tree/6289772626b62957e559c139f42d0cb76d0727f7)

**Comment by coroa** [comment]
Hi tim,

thanks for the heads-up. Turns out the problem is introduced on the CDS side, since it also appears for the actual request `atlite` is sending:
```python
import cdsapi
import xarray as xr

product = 'reanalysis-era5-single-levels'
request = {'product_type': 'reanalysis',
           'format': 'netcdf',
           'day': ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10',
                   '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21',
                   '22', '23', '24', '25', ' 26', '27', '28', '29', '30', '31'],
           'time': ['00:00', '01:00', '02:00', '03:00', '04:00', '05:00',
                    '06:00', '07:00', '08:00', '09:00', '10:00', '11:00', '12:00',
                    '13:00', '14:00', '15:00', '16:00', '17:00', '18:00', '19: 00',
                    '20:00', '21:00', '22:00', '23:00'],
           'area': [71.0, -10.5, 34.5, 34.5],
           'year': 2016,
           'month': 1,
           'variable': ['100m_u_component_of_wind',
                        '100m_v_component_of_wind',
                        '2m_temperature',
                        'runoff',
                        'soil_temperature_level_4',
                        'surface_net_solar_radiation',
                        'surface_pressure',
                        'surface_solar_radiation_downwards',
                        'toa_incident_solar_radiation',
                        'total_sky_direct_solar_radiation_at_surface']}

result = cdsapi.Client().retrieve(
    product,
    request
)

result.download("test.nc")

ds = xr.open_dataset("test.nc")
ds['ro'].to_series().describe()

## Returns
#
# count    1.979561e+07
# mean     1.617490e-05
# std      6.164426e-05
# min     -4.656613e-10
# 25%     -4.656613e-10
# 50%      3.972091e-07
# 75%      1.391862e-05
# max      1.303101e-02
# Name: ro, dtype: float64
```

The problem vanishes if I restrict my request to a single day instead of a month. Testing the exact circumstances is difficult, since the queuing time for requests is in the order of 15min.

I'll introduce a `clip(min=0.)` as a workaround!

**Comment by timtroendle** [comment]
Oh wow, that's nasty! I always tried with one day only and so didn't recognise it was stemming from CDS.

Your workaround sounds good to me. Thanks a lot!

**Comment by timtroendle** [comment]
I discussed this issue with CDS support and was told that it cannot be avoided in their current processing. So I'd assume your workaround is the best one can do.

**Comment by coroa** [comment]
Thanks for the feedback!
