### ISSUE TITLE
[v0.1] Preparing already prepared cutout causes errors

### ISSUE THREAD

**Issue by euronion** [FRESNA/atlite#26]
Using a `cutout` which is already prepared, i.e. with

```
> cutout.available_features == cutout.prepared_features
True
```

and then calling

```
cutout.prepare()
```

results in a lot of activity and finally some errors, e.g.
```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-4-eee9441f41e9> in <module>
----> 1 cutout.prepare()

~/miniconda/envs/atlite-v0.2/lib/python3.7/site-packages/atlite/data.py in cutout_prepare(cutout, features, monthly, overwrite)
    204     if os.path.exists(cutout.cutout_fn):
    205         os.unlink(cutout.cutout_fn)
--> 206     os.rename(target, cutout.cutout_fn)
    207 
    208     # Re-open

FileNotFoundError: [Errno 2] No such file or directory: '/reanalysis/atlite/cutouts/tmp4zn24h_sv0.2_western-asia-2016-era5.nc' -> '../cutouts/v0.2_western-asia-2016-era5.nc'
```

I think the problem is the `data.cutout_prepare(...)` function, which causes a lot of overhead processing, temp-file creation and other things, even if the `missing_features` set at this point is empty
https://github.com/FRESNA/atlite/blob/9f6d0316f20ecd6fffe731d01cd731466845a801/atlite/data.py#L185-L186

I would expect this to run through cleanly in the blink of an eye.
Possibly reintroduce the "Cutout is already fully prepared" fast track from the earlier version?

**Comment by coroa** [comment]
> I would expect this to run through cleanly in the blink of an eye.

Exactly what happens for me.

Can you give me a full log?

**Comment by coroa** [comment]
Doesn't hurt to add a fast-track with an option to re-create the file with `overwrite=True`: https://github.com/FRESNA/atlite/pull/20/commits/c321dae59e083ecdba88b283165c782f738f405d

Can you test with and without overwrite=True?

**Comment by euronion** [comment]
Sure!

* Fast-track from https://github.com/FRESNA/atlite/commit/c321dae59e083ecdba88b283165c782f738f405d is working nicely. (including default `overwrite=False`)
* **`overwrite = True` does not seem to change the behaviour in any direction. Especially it does not seem to overwrite the existing cutout w/ new data.**

I am testing on a Windows 10 and a Linux machine:
With a prepared cutout the Windows 10 machine also does not take long for a subsequent `prepare()` call, but it is doing something.

The linux machine takes significantly longer (although the error disapperared, I might have gotten some interference there from something else before). It does create some temporary files which it later removes and then finishes (doing nothing as the cutout is already prepared).

So I think the fast-track is worth it.

**Comment by coroa** [comment]
Great, then let's leave it in. The `overwrite=True` path is meant for when one adds manually some compression or other changes to cutout.data.attrs or some comments to any of the dataarrays and you want to preserve them.
